define key_A = "{font=Aldrich-Regular.ttf}A:{/font}"
define key_B = "{font=Aldrich-Regular.ttf}B:{/font}"
define key_X = "{font=Aldrich-Regular.ttf}X:{/font}"
define key_Y = "{font=Aldrich-Regular.ttf}Y:{/font}"
define key_LB = "{font=Aldrich-Regular.ttf}LB:{/font}"
define key_LB_2 = "{font=Huayuan.Gothic.Bold.ttf}长按{/font}{font=Aldrich-Regular.ttf}LB{/font}{font=Aldrich-Regular.ttf}:{/font}"
define key_LT = "{font=Aldrich-Regular.ttf}LT:{/font}"
define key_LT_2 = "{font=Huayuan.Gothic.Bold.ttf}长按{/font}{font=Aldrich-Regular.ttf}LT{/font}{font=Aldrich-Regular.ttf}:{/font}"
define key_RB = "{font=Aldrich-Regular.ttf}RB:{/font}"
define key_RB_2 = "{font=Huayuan.Gothic.Bold.ttf}长按{/font}{font=Aldrich-Regular.ttf}RB{/font}{font=Aldrich-Regular.ttf}:{/font}"
define key_RT = "{font=Aldrich-Regular.ttf}RT:{/font}"
define key_RT_2 = "{font=Huayuan.Gothic.Bold.ttf}长按{/font}{font=Aldrich-Regular.ttf}RT{/font}{font=Aldrich-Regular.ttf}:{/font}"
define key_RE = _("{font=Huayuan.Gothic.Bold.ttf}返回键{/font}{font=Aldrich-Regular.ttf}:{/font}")
define key_ST = _("{font=Huayuan.Gothic.Bold.ttf}开始键{/font}{font=Aldrich-Regular.ttf}:{/font}")
define key_UP = _("{font=Huayuan.Gothic.Bold.ttf}十字键上{/font}{font=Aldrich-Regular.ttf}:{/font}")
define key_DOWN = _("{font=Huayuan.Gothic.Bold.ttf}十字键下{/font}{font=Aldrich-Regular.ttf}:{/font}")
define key_LEFT = _("{font=Huayuan.Gothic.Bold.ttf}十字键左{/font}{font=Aldrich-Regular.ttf}:{/font}")
define key_RIGHT = _("{font=Huayuan.Gothic.Bold.ttf}十字键右{/font}{font=Aldrich-Regular.ttf}:{/font}")
define key_LP = _("{font=Huayuan.Gothic.Bold.ttf}左摇杆{/font}{font=Aldrich-Regular.ttf}:{/font}")
define key_RP = _("{font=Huayuan.Gothic.Bold.ttf}右摇杆{/font}{font=Aldrich-Regular.ttf}:{/font}")



define key_mousel = _("{font=Huayuan.Gothic.Bold.ttf}鼠标左键{/font}{font=Aldrich-Regular.ttf}:{/font}")
define key_mouser = _("{font=Huayuan.Gothic.Bold.ttf}鼠标右键{/font}{font=Aldrich-Regular.ttf}:{/font}")
define key_mousec = _("{font=Huayuan.Gothic.Bold.ttf}鼠标中键{/font}{font=Aldrich-Regular.ttf}:{/font}")
define key_mousec_w = _("{font=Huayuan.Gothic.Bold.ttf}鼠标滚轮向前{/font}{font=Aldrich-Regular.ttf}:{/font}")
define key_mousec_s = _("{font=Huayuan.Gothic.Bold.ttf}鼠标滚轮向后{/font}{font=Aldrich-Regular.ttf}:{/font}")
define key_f1 = "{font=Aldrich-Regular.ttf}F1:{/font}"
define key_h = "{font=Aldrich-Regular.ttf}H:{/font}"
define key_q = "{font=Aldrich-Regular.ttf}Q:{/font}"
define key_w = "{font=Aldrich-Regular.ttf}W:{/font}"
define key_f = "{font=Aldrich-Regular.ttf}F:{/font}"
define key_ctrl = "{font=Aldrich-Regular.ttf}Ctrl:{/font}"
define key_tab = "{font=Aldrich-Regular.ttf}Tab:{/font}"
define key_esc = "{font=Aldrich-Regular.ttf}Esc:{/font}"
define key_enter = "{font=Aldrich-Regular.ttf}Enter:{/font}"
define key_ = _("{font=Huayuan.Gothic.Bold.ttf}空格{/font}{font=Aldrich-Regular.ttf}:{/font}")
define key_up = _("{font=Huayuan.Gothic.Bold.ttf}方向键上{/font}{font=Aldrich-Regular.ttf}:{/font}")
define key_down = _("{font=Huayuan.Gothic.Bold.ttf}方向键下{/font}{font=Aldrich-Regular.ttf}:{/font}")
define key_left = _("{font=Huayuan.Gothic.Bold.ttf}方向键左{/font}{font=Aldrich-Regular.ttf}:{/font}")
define key_right = _("{font=Huayuan.Gothic.Bold.ttf}方向键右{/font}{font=Aldrich-Regular.ttf}:{/font}")


define key_text1 = _("{font=Huayuan.Gothic.Bold.ttf}（游戏内）推进剧情。\n（其他）在选中按钮的时候按下按钮。{/font}")
define key_text1_1 = _("{font=Huayuan.Gothic.Bold.ttf}（游戏内）推进剧情。\n（其他）无。{/font}")
define key_text2 = _("{font=Huayuan.Gothic.Bold.ttf}（游戏内）打开游戏菜单。\n（其他）返回上一级菜单。{/font}")
define key_text2_1 = _("{font=Huayuan.Gothic.Bold.ttf}（游戏内）唤出与收起手表UI。\n（其他）返回上一级菜单。{/font}")
define key_text3 = _("{font=Huayuan.Gothic.Bold.ttf}（游戏内）唤出与收起“帮助”菜单。\n（其他）无。{/font}")
define key_text4 = _("{font=Huayuan.Gothic.Bold.ttf}（游戏内）隐藏与显示UI界面。\n（其他）无。{/font}")
define key_text5 = _("{font=Huayuan.Gothic.Bold.ttf}（游戏内）倒退剧情。\n（历史界面）上翻对话记录。{/font}")
define key_text5_1 = _("{font=Huayuan.Gothic.Bold.ttf}（游戏内）倒退剧情。\n（其他）无。{/font}")
define key_text6 = _("{font=Huayuan.Gothic.Bold.ttf}（游戏内）前进已推进过的剧情。\n（历史界面）下翻对话记录。{/font}")
define key_text7 = _("{font=Huayuan.Gothic.Bold.ttf}（游戏内）展开与折叠快捷菜单。\n（其他）无。{/font}")
define key_text8 = _("{font=Huayuan.Gothic.Bold.ttf}（游戏内）唤出与收起手表UI。\n（其他）无。{/font}")
define key_text9 = _("{font=Huayuan.Gothic.Bold.ttf}（游戏内）无。\n（其他）向上选择。{/font}")
define key_text10 = _("{font=Huayuan.Gothic.Bold.ttf}（游戏内）无。\n（其他）向下选择。{/font}")
define key_text11 = _("{font=Huayuan.Gothic.Bold.ttf}（游戏内）无。\n（其他）向左选择。{/font}")
define key_text12 = _("{font=Huayuan.Gothic.Bold.ttf}（游戏内）无。\n（其他）向右选择。{/font}")
define key_text13 = _("{font=Huayuan.Gothic.Bold.ttf}（游戏内）无。\n（其他）向上下左右选择。{/font}")
define key_text14 = _("{font=Huayuan.Gothic.Bold.ttf}（游戏内）快进。\n（其他）无。{/font}")
define key_text14_1 = _("{font=Huayuan.Gothic.Bold.ttf}（游戏内）快进到最后推进的剧情。\n（其他）无。{/font}")
define key_text14_2 = _("{font=Huayuan.Gothic.Bold.ttf}（游戏内）持续快进。\n（其他）无。{/font}")
define key_text15 = _("{font=Huayuan.Gothic.Bold.ttf}（游戏内）快退。\n（其他）无。{/font}")
define key_text16 = _("{font=Huayuan.Gothic.Bold.ttf}（全局）切换全屏/窗口化。\n（其他）无。{/font}")